backend = "glx";
vsync = true;
use-damage = false;
detect-client-opacity = true;
mark-wmwin-focused = true;
mark-ovredir-focused = false;

shadow = false;
shadow-radius = 0;
shadow-opacity = 0.0;
shadow-offset-x = 0;
shadow-offset-y = 0;
shadow-color = "#000000";
shadow-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dwm-systray'",
	"class_g = 'slop'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'menu'",
	"window_type = 'dropdown_menu'",
	"window_type = 'popup_menu'",
	"window_type = 'tooltip'",
	"window_type = 'notification'",
	"_GTK_FRAME_EXTENTS@"
];

fading = true;
fade-in-step = 0.075;
fade-out-step = 0.075;
fade-delta = 5;
fade-exclude = [ "class_g = 'dwm'", "class_g = 'dmenu'", "class_g = 'slock'" ];

inactive-opacity = 0.88;
active-opacity = 0.92;
frame-opacity = 0.92;
inactive-opacity-override = false;
opacity-rule = [
	"100:fullscreen",
	"100:class_g = 'mpv'",
	"100:class_g = 'cs2'",
	"100:class_g = 'slock'",
	"100:class_g = 'dmenu'",
	"100:class_g = 'dwm-systray'",
	"100:class_g = 'slop'",
	"100:window_type = 'dock'",
	"100:window_type = 'tooltip'",
	"92:class_g = 'st'",
	"92:class_g = 'float'",
	"94:window_type = 'normal'"
];

blur-method = "gaussian";
blur-size = 18;
blur-deviation = 8.0;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = true;
blur-background-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dwm-systray'",
	"class_g = 'dmenu'",
	"class_g = 'slop'",
	"class_g = 'slock'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'tooltip'"
];

corner-radius = 0;
rounded-corners-exclude = [
	"class_g = 'dwm'",
	"class_g = 'dwm-systray'",
	"class_g = 'dmenu'",
	"class_g = 'slop'",
	"class_g = 'slock'",
	"window_type = 'dock'",
	"window_type = 'desktop'",
	"window_type = 'tooltip'",
	"window_type = 'notification'",
	"window_type = 'unknown'",
	"override_redirect = true"
];
