font_family      SpaceMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.5

cursor_shape beam
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.08 0.25
cursor_trail_start_threshold 1
cursor_trail_color #ffcc66
enable_audio_bell no
window_padding_width 8
background_opacity 1.0
dynamic_background_opacity yes
transparent_background_colors #1f2430@1.0 #252b38@1.0

foreground #cbccc6
background #1f2430
selection_foreground #1f2430
selection_background #ffcc66
cursor #ffcc66
cursor_text_color #1f2430

color0  #1f2430
color1  #f28779
color2  #bae67e
color3  #ffd580
color4  #73d0ff
color5  #d4bfff
color6  #95e6cb
color7  #cbccc6
color8  #707a8c
color9  #f28779
color10 #bae67e
color11 #ffd580
color12 #73d0ff
color13 #d4bfff
color14 #95e6cb
color15 #ffffff
